return PlaceObj('ModDef', {
	'title', "Vanilla Perks Expanded",
	'description', '[h2]Overview[/h2]\nThis mod aims to bring more variety on builds and personalization of your mercs, you can build from melee fighters to modern John Wick gunslingers.Also, rebalance and rework some of vanilla traits.\n\n[h1]Vanilla Perks Remastered (WIP)[/h1]\n[h3]Features[/h3]\n[list]\n	[*]New Perk tree based on skills\n    [*]New option "Enemy Roles": it adds the roles to enemies, it can make the game harder. It uses the same logic to assign the roles to mercs\n    [*]New option "10+ Level Icons"\n[/list]\n[h3][i]List of changes[/i][/h3]\n[list]\n    [*]Gunslinger: Increased Range (flat bonus) for handguns, increases damage (scales with level), increases CTH (scales), reduces ap for shooting by 1\n    [*](buff)HawksEye(Scope): Increases the range for all rifles, scaled/level\n    [*](buff)BunsPerk(Buns): same as above but only after level 6\n    [*](buff)KalynaPerk(Kalyna): same as above but after level 3, Kalyna is a expensive merc for no special reason and struggles after a few levels as her stats are too low to open new traits and her wisdom abysmal for be trained quickly.\n    [*](QoL)SteroidPunch(Steroid) - no longer require unarmed\n    [*](QoL)ExplodingPalm(DrQ) - same as above\n    [*](buff)SteadyBreathing(Fast Runner) - extends its benefits to medium armor\n    [*](rework)InnerInfo(Livewire) - Replaced by "Hack the System!" bonus CTH for hacking. I like playing with her but her perk makes the game too easy no matter the difficult, bonus is capped at 20. If you scrap her PDA she will lose the bonus.\n    [*](buff)JackOfAllTrades(Wolf) - adds 2% damage resistance/level\n    [*](rework)AutoWeapons: - no longer works for pistols or machineguns, keeps the bonus for autofire and adds the following, Increased range for SMG(flat), Increased range for AR(scaled), reduce 1 ap for attacks on the same target with ARs(single shot only), New combat action for "AutoWeapons": BARRAGE, (SMGs only)\n    [*](rework)Berserker(Rage) - replaced by "Endurance", grants damage resistance/stacks instead of damage.Note that some enemies also have this trait so it can affect the gameplay\n    [*](buff)LightStep(Mouse) - adds the following: auto-hide after killing an unit at level 4, auto-hide at the end of its turn at level 6, auto-hide after taking damage at level 8. She will remain hidden if not in standing position, other cases she will be revealed (she isn\'t Shadow)\n    [*](rework)HeavyWeaponsTraining(Heavy Weapons) - adds the following: reduces the penalty for autofire with MGs, grants half of free move if using cumbersome equipment,\n    [*](new perk)Sharpshooter: Increased CTH for aimed attacks, increased range for Snipers and Rifles, Reduced Ap for shooting in crouch or prone positions.\n    [*](rework)Lightning Reactions("LightningReaction") - no longer goes prone, CHANCE to proc once per turn (25% at level 10), does not affect NPCs(Santiago and Major have this trait tho), it scales with level and agility\n    [*](nerf)Lightnings Reactions("LightningReactionNPC") - still works the same way now there are more conditions to proc (ex. can\'t be surprised) \n    [*](buff)HitTheDeck("Hit the deck"): reduces the penalty from moving in prone or crouch positions\n	[*](new perk)BurstControl - Increases number of shots and damage for burst attacks.\n[/list]\n\n[h3][i]New mechanic "Roles"[/i][/h3]\nThese roles are based on the vanilla game, I assigned the roles to the respectively mercs accordingly with the base vanilla game, although I disagree in some points. The roles have inherent bonuses that scales with your level, the same apply for your enemies, if you want a more balanced experience please enable the option EnemyRoles\n[list]\n    [*]Leader: bonus morale for allies around him\n    [*]All Rounder: damage resistance against close targets, it decreases with distance, concept is add bonus attacks and wider angle for overwatch with medium range weapons\n    [*]Doctor: additional damage against light armored targets\n    [*]Mechanic: additional damage against heavy armored targets\n    [*]Explosive Expert:(not implemented): [i]still working on it[/i]\n    [*]Marksman: bonus damage and CTH\n[/list]\n[h3][i]Vanilla perks changes[/i][/h3]\nThis are vanilla perks that I changed the category, means that the perk works the same as vanilla but now have a different category and requisites.\n[list]\n    [*]Ambidextrious -> Marksmanship\n    [*]CQC -> Marksmanship\n    [*]OverwatchExpert -> Marksmanship\n	[*]SharpInstincts -> Medical\n	[*]SixthSense -> Medical\n	[*]Throwing -> Explosives\n	[*]Teacher -> Leadership\n	[*]MrFixit -> Mechanical\n	[*]Negotiator -> Leadership\n	[*]NaturalCamouflage(this is the only one in this list that I tweaked the value from 40 to 20) -> Medical\n[/list]\n[i]Why these weird traits that require medical?[/i]\nI tested changing the vanilla perk tree and did not worked well, (trust me there are things in this game that you don\'t want to tamper with) so I decided to use the Medical tree an random tree, for perks that are not so specific but very impactful\n[h3]Progression table for Roles[/h3]\n(+1/level or +2/level or +1/2 level and so on) - not implemented yet\nRoles at level 10 (max for vanilla settings)\n[i]Marksman[/i]\n+10 CTH Ranged Weapons\n+10 DMG Ranged Weapons\n[i]All Rounder[/i]\n+10% Damage Resistance\n[i]Mechanic[/i]\n+5 CTH Ranged Weapons (not implemented)\n+5 DMG Ranged Weapons (not implemented)\n+5 CTH Melee Weapons (not implemented)\n+5 DMG Melee Weapons (not implemented)\n+10 DMG Against Armored targets (heavy armor)\n[i]Medic[/i]\n+5 Damage Resistance (not implemented)\n+3 Movement Speed (not implemented)\n+5 DMG Against Armored targets (light armor)\n[i]Leader[/i]\n+5 CTH Ranged Weapons  (not implemented)\n+5 DMG Ranged Weapons  (not implemented)\n+5 CTH Melee Weapons  (not implemented)\n+5 DMG Melee Weapons  (not implemented)\n+5 DMG Resistance  (not implemented)\nInspiring Aura (Bonus Morale, range increases with level)\n[i]Explosive Expert[/i]\n+2 Max Range for grenades  (not implemented)\n+5 Damage Resistance  (not implemented)\n[hr][/hr]\n[h3]Related Mods[/h3]\n[list]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3239743887] Grand Chien Expanded <3[/url]\n		[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3239859485] Vanilla Weapons Expanded[/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3238572469] Vanilla Weapons Expanded - Quest Items [/url]\n		[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3253641552] Vanilla Battles Enhanced [/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3238546616] Random Attack [/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3238563037] Diamond Briefcase Enhanced [/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3238744119] Enhanced Kompositum [/url]\n[/list]\n[hr][/hr]\n[h3] Immersion mods [/h3]\n[list]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3238535853] Learn to Like Me [/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3242501087] Suit Up[/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3253711922] Baby Don\'t You Lie to Me [/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3260806453] Audaki’s Training Overhaul[/url]\n[/list]\n[hr][/hr]\n[h3] Other [/h3]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3255590356] Hat of Tricks[/url]',
	'image', "Mod/PerksExpanded/Images/Screenshot 2024-06-01 132517.png",
	'external_links', {
		"https://github.com/yasumitsu/Vanilla-Perks-Expanded",
	},
	'last_changes', "- changed prerequisites of several perks",
	'dependencies', {},
	'id', "PerksExpanded",
	'author', "Sir Ni",
	'version_major', 2,
	'version_minor', 2,
	'version', 1894,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/GiveMeARole.lua",
		"Code/LevelIcons.lua",
		"Code/GetInitialMaxHitPoints.lua",
		"Code/Doctor.lua",
		"Code/UseItems.lua",
		"Code/Barrage.lua",
		"Code/UnitActionBarrage.lua",
		"Code/Dodge.lua",
		"Code/ChangePerks.lua",
		"Code/CanUnlockSkills.lua",
		"Code/MGLBombard.lua",
		"Code/GetAllAttributes.lua",
		"CharacterEffect/LightningReaction.lua",
		"CharacterEffect/Untraceable.lua",
		"CharacterEffect/MartialArts.lua",
		"CharacterEffect/Berserker.lua",
		"CharacterEffect/SteadyBreathing.lua",
		"CharacterEffect/NightOps.lua",
		"CharacterEffect/NaturalCamouflage.lua",
		"CharacterEffect/SharpInstincts.lua",
		"CharacterEffect/SixthSense.lua",
		"CharacterEffect/HitTheDeck.lua",
		"CharacterEffect/BreachAndClear.lua",
		"CharacterEffect/HeavyWeaponsTraining.lua",
		"CharacterEffect/Throwing.lua",
		"CharacterEffect/Teacher.lua",
		"CharacterEffect/ShockAndAwe.lua",
		"CharacterEffect/LeadFromTheFront.lua",
		"CharacterEffect/LastWarning.lua",
		"CharacterEffect/StressManagement.lua",
		"CharacterEffect/Negotiator.lua",
		"CharacterEffect/Enfilade.lua",
		"CharacterEffect/Sharpshooter.lua",
		"CharacterEffect/BurstControl.lua",
		"CharacterEffect/AutoWeapons.lua",
		"CharacterEffect/Gunslinger.lua",
		"CharacterEffect/OverwatchExpert.lua",
		"CharacterEffect/CQCTraining.lua",
		"CharacterEffect/Ambidextrous.lua",
		"CharacterEffect/MrFixit.lua",
		"CharacterEffect/TrickShot.lua",
		"CharacterEffect/Caretaker.lua",
		"CharacterEffect/Hobbler.lua",
		"CharacterEffect/Savior.lua",
		"CharacterEffect/LightStep.lua",
		"CharacterEffect/JackOfAllTrades.lua",
		"CharacterEffect/HawksEye.lua",
		"CharacterEffect/BunsPerk.lua",
		"CharacterEffect/KalynaPerk.lua",
		"CharacterEffect/InnerInfo.lua",
		"CharacterEffect/AllRounder.lua",
		"CharacterEffect/Doctor.lua",
		"CharacterEffect/Leader.lua",
		"CharacterEffect/Marksman.lua",
		"CharacterEffect/Mechanic.lua",
		"CharacterEffect/ExplosiveExpert.lua",
		"CharacterEffect/LightningReactionNPC.lua",
		"InventoryItem/CustomPDA.lua",
		"InventoryItem/SkillMag_Regen.lua",
		"InventoryItem/SkillMag_Survival.lua",
		"CharacterEffect/BonusHPRoles.lua",
		"CharacterEffect/DoubleTapPistol.lua",
		"CharacterEffect/DoubleTap.lua",
		"CharacterEffect/LeaderAuraBuff.lua",
		"CharacterEffect/LeaderAuraDebuff.lua",
		"CharacterEffect/HitTheDeckMoveMod.lua",
		"CharacterEffect/SurvivalInstinct.lua",
		"CharacterEffect/Regen.lua",
		"CharacterEffect/Endurance.lua",
		"CharacterEffect/ShamanArmor.lua",
		"CharacterEffect/Stealthy_1.lua",
	},
	'default_options', {
		EnemyRoles = true,
		LevelIcons = true,
	},
	'has_data', true,
	'saved', 1719057617,
	'code_hash', -5991492514840524197,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "GameRuleDef",
			'Id', "AdditionalPerks",
			'ClassDisplayName', "Game rule",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "LightningReaction",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Untraceable",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "MartialArts",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Berserker",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "SteadyBreathing",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "NightOps",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "NaturalCamouflage",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "SharpInstincts",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "SixthSense",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "HitTheDeck",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "BreachAndClear",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "HeavyWeaponsTraining",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Throwing",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Teacher",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ShockAndAwe",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "LeadFromTheFront",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "LastWarning",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "StressManagement",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Negotiator",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Enfilade",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Sharpshooter",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "BurstControl",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "AutoWeapons",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Gunslinger",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "OverwatchExpert",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "CQCTraining",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Ambidextrous",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "MrFixit",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "TrickShot",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Caretaker",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Hobbler",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Savior",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "LightStep",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "JackOfAllTrades",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "HawksEye",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "BunsPerk",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "KalynaPerk",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "InnerInfo",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "AllRounder",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Doctor",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Leader",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Marksman",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Mechanic",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ExplosiveExpert",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "LightningReactionNPC",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "BulletHell",
			'Prop', "GetActionResults",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "ExplodingPalm",
			'Prop', "GetAttackWeapons",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "SteroidPunch",
			'Prop', "GetAttackWeapons",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "CustomPDA",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "SkillMag_Regen",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "SkillMag_Survival",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "BonusHPRoles",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "DoubleTapPistol",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "DoubleTap",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "LeaderAuraBuff",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "LeaderAuraDebuff",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "HitTheDeckMoveMod",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "SurvivalInstinct",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Regen",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Endurance",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ShamanArmor",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Barry",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Blood",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Buns",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "DrQ",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Fauda",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Fidel",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Flay",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Fox",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Grizzly",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Grunty",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Gus",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Hitman",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Ice",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Igor",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Ivan",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Kalyna",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Larry",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Larry_Clean",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Len",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Livewire",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "MD",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Magic",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Meltdown",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Mouse",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Nails",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Omryn",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Pierre",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "PierreMerc",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Raider",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Raven",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Reaper",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Red",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Scope",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Scully",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Shadow",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Sidney",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Smiley",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "SmileyNPC",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "TheMajor",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Spike",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Steroid",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Thor",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Tex",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Vicki",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "Wolf",
			'Prop', "StartingPerks",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CombatAction",
			'Id', "InnerInfo",
			'Prop', "Icon",
			'ClassDisplayName', "Combat Action",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDAAimEvaluation",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDAPerks",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "CyberEnhancement",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Stealthy_1",
			'ClassDisplayName', "Character effect",
		}),
	},
	'steam_id', "3239224340",
	'TagBalancing&Difficulty', true,
	'TagMercs', true,
	'TagPerks&Talents&Skills', true,
})